Repository NexusGPU/tensor-fusion, pull requests merged in 2025-05, with the labels that each got.

#179 fix: prevent release gpu failure
  internal/controller/tensorfusionworkload_controller.go
Labels: bug, go

#184 chore: change Dependabot Go module updates to weekly
  .github/dependabot.yml
Labels: dependencies

#201 feat: print version when start operator
  .github/workflows/release.yml
  cmd/main.go
  dockerfile/operator.Dockerfile
  internal/version/version.go
Labels: enhancement, go, github_actions
